In [30]:
# Import Numpy & PyTorch
import numpy as np
import torch
from numpy.core.fromnumeric import mean

In [31]:
#Input (temp, rainfall, humidity)
inputs = np.array([
            [73,67,43],
            [91,88,64],
            [87,134,58],
            [102,43,37],
            [69,96,70]
        ],dtype='float32')

In [32]:
targets = np.array([
            [56],
            [81],
            [119],
            [22],
            [103]
        ],dtype='float32')

In [33]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [34]:
w = torch.randn(1,3, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(w,'\n',b)

tensor([[-1.0727, -1.1578,  1.2446]], requires_grad=True) 
 tensor([0.3334], requires_grad=True)


In [35]:
def model(x):
    return torch.mm(x,w.t(),out=None) + b

In [36]:
pred = model(inputs)
print(pred)
print(targets)

tensor([[-102.0294],
        [-119.5159],
        [-175.9516],
        [-112.8173],
        [ -97.7119]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [37]:
def MSE(P, T) :
    diff = i = sum = 0
    n = len(T)
    for j in range(0,n) :
        sum += (T[j] - P[j]) * (T[j] - P[j])
    mean = sum/n
    return mean

result = MSE(pred, targets)
print(result) 

tensor([42127.4609], grad_fn=<DivBackward0>)


In [38]:
result.backward()
print(w.grad)
print(b.grad)

tensor([[-33217.7461, -37128.9492, -22309.4180]])
tensor([-395.6104])


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a44cab79-508d-4bfc-9679-af4d4af7e346' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>