In [1]:
import numpy as np
import random

In [2]:
# Create a Numpy array of size 4 x 5.

alist = [0] * 4

#Randomly initialize the array.
for i in range(4):
  alist[i] = []
  for j in range(5):
    alist[i].append(np.random.randint(0,20))
    
narray = np.array(alist)

print(alist)

[[19, 19, 12, 12, 16], [7, 6, 6, 16, 7], [18, 9, 17, 0, 5], [13, 7, 9, 8, 2]]


In [3]:
#Get the Transpose of the Matrix that you created. 

print(narray.T)

[[19  7 18 13]
 [19  6  9  7]
 [12  6 17  9]
 [12 16  0  8]
 [16  7  5  2]]


In [4]:
#Create a square matrix and find its determinant.

#matrix3 = np.matrix(np.random.rand(4,4))
matrix3 = np.matrix(narray.T[0:4])
print(matrix3)
print("\nDeterminant is : " , np.linalg.det(matrix3))

[[19  7 18 13]
 [19  6  9  7]
 [12  6 17  9]
 [12 16  0  8]]

Determinant is :  7712.000000000002


In [5]:
# Create another matrix of size 5 x 4 and randomly initialize it.
# Perform Matrix multiplication.
# Perform element wise matrix multiplication.
#Matrix1 = np.matrix(np.random.rand(5,4))
Matrix1 = np.matrix(narray.T)
print("Matrix 1 : \n",Matrix1)
#Matrix2 = np.matrix(np.random.rand(4,5))
Matrix2 = np.matrix(narray[0:4])
print("\nMatrix 2 : \n", Matrix2)

res = Matrix1 * Matrix2
print("\nMatrix Multiplication :\n", res)

mul = np.multiply(Matrix1, Matrix1)
print("\nElement wise Multiplication Mat1 : \n" , mul)

Matrix 1 : 
 [[19  7 18 13]
 [19  6  9  7]
 [12  6 17  9]
 [12 16  0  8]
 [16  7  5  2]]

Matrix 2 : 
 [[19 19 12 12 16]
 [ 7  6  6 16  7]
 [18  9 17  0  5]
 [13  7  9  8  2]]

Matrix Multiplication :
 [[903 656 693 444 469]
 [656 527 480 380 405]
 [693 480 550 312 337]
 [444 380 312 464 320]
 [469 405 337 320 334]]

Element wise Multiplication Mat1 : 
 [[361  49 324 169]
 [361  36  81  49]
 [144  36 289  81]
 [144 256   0  64]
 [256  49  25   4]]


In [6]:
#Find mean, median of the numpy array created.
mean = np.mean(narray)
print("Mean of narray : \n",mean)

median = np.median(narray)
print("\nMedian of narray : \n",median)

Mean of narray : 
 10.4

Median of narray : 
 9.0


In [7]:
#Obtain each row in the second column of the first array.

print(narray)
print("\nRows of 2nd Column ",narray[0:,1])

[[19 19 12 12 16]
 [ 7  6  6 16  7]
 [18  9 17  0  5]
 [13  7  9  8  2]]

Rows of 2nd Column  [19  6  9  7]


In [8]:
#Convert Numeric entries(columns) of Iris.csv to Mean Centered Version
import pandas as pd

data=pd.read_csv('https://raw.githubusercontent.com/ShyamCE/machine_learning/main/Classroom_files/Lab-1/Iris.csv')

arr1=np.array(data.head(5))
#print("\narr1 : ",arr1);

mat4=np.array([arr1[:,0],arr1[:,1],arr1[:,2],arr1[:,3],arr1[:,4]])
#print("\nmat4 : ",mat4)

#column axis = 0 , row axis = 1
res=mat4-np.mean(mat4,axis=0)

print(res)

[[-1.2399999999999998 -0.2999999999999998 0.52 1.3200000000000003 1.96]
 [2.86 2.6000000000000005 2.22 1.92 1.96]
 [1.2600000000000002 0.7000000000000002 0.7200000000000002
  0.4200000000000004 0.56]
 [-0.8399999999999999 -0.8999999999999999 -1.18 -1.1799999999999997
  -1.6400000000000001]
 [-2.0399999999999996 -2.0999999999999996 -2.28 -2.4799999999999995 -2.84]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a44cab79-508d-4bfc-9679-af4d4af7e346' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>