In [2]:
import numpy as np
import random

In [11]:
# Create a Numpy array of size 4 x 5.

alist = [0] * 4

#Randomly initialize the array.
for i in range(4):
  alist[i] = []
  for j in range(5):
    alist[i].append(np.random.randint(0,20))
    
narray = np.array(alist)

print(alist)

[[14, 13, 18, 9, 4], [14, 9, 5, 9, 6], [14, 10, 6, 8, 13], [4, 4, 3, 3, 7]]


In [9]:
#Get the Transpose of the Matrix that you created. 

print(narray.T)

[[ 2 13 15 15]
 [ 1  0 19  4]
 [14  1  9  8]
 [18  5  9  2]
 [ 2 17  7 13]]


In [35]:
#Create a square matrix and find its determinant.

#matrix3 = np.matrix(np.random.rand(4,4))
matrix3 = np.matrix(narray.T[0:4])
print(matrix3)
print("\nDeterminant is : " , np.linalg.det(matrix3))

[[14 14 14  4]
 [13  9 10  4]
 [18  5  6  3]
 [ 9  9  8  3]]

Determinant is :  225.9999999999999


In [34]:
# Create another matrix of size 5 x 4 and randomly initialize it.
# Perform Matrix multiplication.
# Perform element wise matrix multiplication.
#Matrix1 = np.matrix(np.random.rand(5,4))
Matrix1 = np.matrix(narray.T)
print("Matrix 1 : \n",Matrix1)
#Matrix2 = np.matrix(np.random.rand(4,5))
Matrix2 = np.matrix(narray[0:4])
print("\nMatrix 2 : \n", Matrix2)

res = Matrix1 * Matrix2
print("\nMatrix Multiplication :\n", res)

mul = np.multiply(Matrix1, Matrix1)
print("\nElement wise Multiplication Mat1 : \n" , mul)

Matrix 1 : 
 [[14 14 14  4]
 [13  9 10  4]
 [18  5  6  3]
 [ 9  9  8  3]
 [ 4  6 13  7]]

Matrix 2 : 
 [[14 13 18  9  4]
 [14  9  5  9  6]
 [14 10  6  8 13]
 [ 4  4  3  3  7]]

Matrix Multiplication :
 [[604 464 418 376 350]
 [464 366 351 290 264]
 [418 351 394 264 201]
 [376 290 264 235 215]
 [350 264 201 215 270]]

Element wise Multiplication Mat1 : 
 [[196 196 196  16]
 [169  81 100  16]
 [324  25  36   9]
 [ 81  81  64   9]
 [ 16  36 169  49]]


In [37]:
#Find mean, median of the numpy array created.
mean = np.mean(narray)
print("Mean of narray : \n",mean)

median = np.median(narray)
print("\nMedian of narray : \n",median)

Mean of narray : 
 8.65

Median of narray : 
 8.5


In [36]:
#Obtain each row in the second column of the first array.

print(narray)
print("\nRows of 2nd Column ",narray[0:,1])

[[14 13 18  9  4]
 [14  9  5  9  6]
 [14 10  6  8 13]
 [ 4  4  3  3  7]]

Rows of 2nd Column  [13  9 10  4]


In [38]:
#Convert Numeric entries(columns) of Iris.csv to Mean Centered Version
import pandas as pd

data=pd.read_csv('https://raw.githubusercontent.com/shyamPatel99/machine_learning/main/csv_file/Iris.csv')

arr1=np.array(data.head(5))
#print("\narr1 : ",arr1);

mat4=np.array([arr1[:,0],arr1[:,1],arr1[:,2],arr1[:,3],arr1[:,4]])
#print("\nmat4 : ",mat4)

#column axis = 0 , row axis = 1
res=mat4-np.mean(mat4,axis=0)

print(res)

[[-1.2399999999999998 -0.2999999999999998 0.52 1.3200000000000003 1.96]
 [2.86 2.6000000000000005 2.22 1.92 1.96]
 [1.2600000000000002 0.7000000000000002 0.7200000000000002
  0.4200000000000004 0.56]
 [-0.8399999999999999 -0.8999999999999999 -1.18 -1.1799999999999997
  -1.6400000000000001]
 [-2.0399999999999996 -2.0999999999999996 -2.28 -2.4799999999999995 -2.84]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a44cab79-508d-4bfc-9679-af4d4af7e346' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>